CREATE TABLE IF NOT EXISTS public.comentario
(
    id_comentario bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    corpo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    curtidas integer,
    id_dica bigint,
    id_usuario bigint,
    CONSTRAINT comentario_pkey PRIMARY KEY (id_comentario),
    CONSTRAINT fk90pt5t4wt415puhpscsjwsunt FOREIGN KEY (id_dica)
        REFERENCES public.dica (id_dica) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk9619kv3mim3a4yl0m5mdhhbh1 FOREIGN KEY (id_usuario)
        REFERENCES public.usuario (id_usuario) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.comentario
    OWNER to postgres;